### ISSUE TITLE
Unable to evaluate a namespaced xpath

### ISSUE THREAD

**Issue by sanpii** [shepmaster/sxd-xpath#108]
Hello,

I have an error when I try to evaluate a namespaced xpath:

```
$ cargo run
   Compiling quick-error v1.1.0
   Compiling typed-arena v1.2.0
   Compiling peresil v0.3.0
   Compiling sxd-document v0.2.0
   Compiling sxd-xpath v0.4.0 (https://github.com/shepmaster/sxd-xpath.git#16b17d77)
   Compiling rust v0.1.0 (file:///home/sanpi/test/rust)
    Finished debug [unoptimized + debuginfo] target(s) in 8.74 secs
     Running `target/debug/rust`
thread 'main' panicked at 'No namespace for prefix', /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libcore/option.rs:715
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

```rust
extern crate sxd_document;
extern crate sxd_xpath;

fn main() {
    let package = ::sxd_document::parser::parse(r#"
<d:multistatus xmlns:d="DAV:" xmlns:cs="http://calendarserver.org/ns/">
    <d:response>
        <d:href>/</d:href>
        <d:propstat>
            <d:prop>
                <d:current-user-principal>
                    <d:href>/principals/users/johndoe/</d:href>
                </d:current-user-principal>
            </d:prop>
            <d:status>HTTP/1.1 200 OK</d:status>
        </d:propstat>
    </d:response>
</d:multistatus>"#).unwrap();

    let document = package.as_document();

    ::sxd_xpath::evaluate_xpath(&document, "/d:multistatus")
        .unwrap();
}
```

**Comment by shepmaster** [comment]
That's correct; there's nothing that ties the prefixes in the XPath to the prefixes in the document. Prefixes are meant as a **localized** shorthand for a namespace. You wouldn't want your program to stop working if the input document decided to start using `D` as the prefix.

As the documentation states:

> For more complex needs, XPath parsing and evaluation can be split apart. This allows the user to specify namespaces, variables, extra functions, and which node evaluation should begin with. You may also compile an XPath once and reuse it multiple times.

The [documentation for `Context`](https://docs.rs/sxd-xpath/0.4.0/sxd_xpath/context/struct.Context.html) further shows how to configure this.

**Comment by shepmaster** [comment]
> You wouldn't want your program to stop working if the input document decided to start using D as the prefix.

Furthermore, what would you expect for the XPath `//d:*` to return with the XML:

```xml
<d:root xmlns:d="uri://outer">
  <d:child xmlns:d="uri://inner" />
</d:root>
```

**Comment by sanpii** [comment]
Thank you, that works fine with an appropriate context.

**Comment by shepmaster** [comment]
Thank you for providing an easy-to-follow example!

**Comment by sanpii** [comment]
```rust
extern crate sxd_document;
extern crate sxd_xpath;


fn main() {
    let package = ::sxd_document::parser::parse(r#"
<d:multistatus xmlns:d="DAV:" xmlns:cs="http://calendarserver.org/ns/">
    <d:response>
        <d:href>/</d:href>
        <d:propstat>
            <d:prop>
                <d:current-user-principal>
                    <d:href>/principals/users/johndoe/</d:href>
                </d:current-user-principal>
            </d:prop>
            <d:status>HTTP/1.1 200 OK</d:status>
        </d:propstat>
    </d:response>
</d:multistatus>
"#).unwrap();

    let document = package.as_document();
    let root = document.root().children()[0];

    let mut context = ::sxd_xpath::Context::new();
    context.set_namespace("d", "DAV:");

    let factory = ::sxd_xpath::Factory::new();

    let xpath = factory.build("/d:multistatus")
        .expect("Could not compile XPath")
        .expect("No XPath was compiled");

    xpath.evaluate(&context, root)
        .unwrap();
}
```

**Comment by shepmaster** [comment]
I did forget to mention that it's possible to write code that does the original request. You'd have to take the document, grab the root, then the topmost element, iterate over all the namespaces, then register those URIs and prefixes on the context. However, you still run into the risks of a mis-matched.

I've thought about adding some code like this for the little XPath utility that ships with the library, as it's very useful when you are exploring an XML file on the command line.
