### ISSUE TITLE
Investigate whether core functions should implicitly convert to boolean or number types

### ISSUE THREAD

**Issue by shepmaster** [shepmaster/sxd-xpath#114]
As seen in #113, core functions seem to convert to strings, but should we do the same for booleans and numbers?

**Comment by akovaski** [comment]
Unless I am misinterpreting the XPath spec, the answer is 'Yes, try to convert to strings, booleans, and numbers'.

See section 3.2 "Function Calls" from the spec: https://www.w3.org/TR/xpath/#section-Function-Calls
Specifically:

>  It is an error if the number of arguments is wrong or if an argument cannot be converted to the required type.
...
> An argument is converted to type string as if by calling the string function. An argument is converted to type number as if by calling the number function. An argument is converted to type boolean as if by calling the boolean function. An argument that is not of type node-set cannot be converted to a node-set.

**Comment by shepmaster** [comment]
@akovaski thank you! I'll go ahead and change all the functions to perform transformations automatically.
