### ISSUE TITLE
xml declaration is causing InvalidProcessingInstructionTarget

### ISSUE THREAD

**Issue by maximih** [shepmaster/sxd-xpath#63]
Hi

I tried `sxd-xpath` and I noticed it doesn't seem to support [xml declarations](https://msdn.microsoft.com/en-us/library/ms256048%28v=vs.110%29.aspx).

The code is based on the syntax used for the crate's tests:

```
extern crate sxd_xpath;
extern crate sxd_document;

use std::collections::HashMap;
use sxd_document::Package;
use sxd_document::dom::Document;
use sxd_document::parser::Parser;
use sxd_xpath::{Value,Functions,Variables,Namespaces,Factory,EvaluationContext,Expression};


fn main() {
    let x = r#"
<?xml version="1.0" encoding="UTF-8"?>

<bookstore>

<book>
  <title lang="en">Harry Potter</title>
  <price>29.99</price>
</book>

<book>
  <title lang="en">Learning XML</title>
  <price>39.95</price>
</book>

</bookstore>"#;
let package = parse(x);
let doc = package.as_document();
let result = evaluate(&doc, "string(/*/book[1]/title/@lang)");
println!("{:?}", &result);
}

fn parse(xml: &str) -> Package {
    Parser::new().parse(xml).unwrap()
}

fn evaluate<'d>(package: &'d Document<'d>, xpath: &str) -> Value<'d> {
    let setup = Setup::new();
    setup.evaluate(package, xpath)
}

struct Setup<'d> {
    functions: Functions,
    variables: Variables<'d>,
    namespaces: Namespaces,
    factory: Factory,
}

impl<'d> Setup<'d> {
    fn new() -> Setup<'d> {
        let mut fns = HashMap::new();
        sxd_xpath::function::register_core_functions(&mut fns);
        Setup {
            functions: fns,
            variables: HashMap::new(),
            namespaces: HashMap::new(),
            factory: Factory::new(),
        }
    }

    fn evaluate(&self, doc: &'d Document<'d>, xpath: &str) -> Value<'d> {
        let root = doc.root();
        let context = EvaluationContext::new(
            root,
            &self.functions,
            &self.variables,
            &self.namespaces,
        );

        let xpath = self.factory.build(xpath).unwrap().unwrap();
        xpath.evaluate(&context).ok().unwrap()
    }
}
```

When I run it:

```
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: (3, [InvalidProcessingInstructionTarget])', /Users/rustbuild/src/rust-buildbot/slave/stable-dist-rustc-mac/build/src/libcore/result.rs:729
```

Everything works as expected if I remove the XML declaration (`<?xml version="1.0" encoding="UTF-8"?>`)  from the xml string.

I don't know if there is already a nice way to avoid this error, as the documentation is a bit scarce. I would like to help out with a PR but I just started playing with the lib so I am not familiar at all with the design.

**Comment by shepmaster** [comment]
This is a tricky nuance of the XML spec, and the error message certainly doesn't help out much here!

The root problem is that the XML declaration needs to be the *very* first thing in the document, but you've got a newline before the declaration:

```rust
let x = r#"
<?xml version="1.0" encoding="UTF-8"?>
```

I think if you just pull it up, you will be good to go:

```rust
let x = r#"<?xml version="1.0" encoding="UTF-8"?>
```

libxml has a more user-friendly error message:

> XML declaration allowed only at the start of the document

I've got unpushed work where I am changing exactly how and where this error originates, and I might do a bit of work to get user-readable error messages in there!

**Comment by shepmaster** [comment]
> as the documentation is a bit scarce

That's a very polite understatement! Maybe this would be a useful place to submit some PRs? Documentation is always the last thing a developer does, but the first thing the user checks out!

> I just started playing with the lib

This will also be useful - I've been building it from the inside-out, with only the lightest of attention paid to how ergonomic it is to use. Any feedback would be great here!

**Comment by maximih** [comment]
Hi. Thanks for the quick answer. I've actually got bitten by this error in the past but apparently I have a short memory :).

Regarding ergonomicity, the first suggestion I have is to add high level function or a macro to hide all that code in the example (the `struct Setup` and its `impl`), e.g `fn evaluate (..) -> Result<_, _>`. Apologies if there is such a high level fn already and I didn't find it.
